import { create } from 'zustand';

type Language = 'tr' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  tr: {
    'nav.shop': 'Mağaza',
    'nav.producers': 'Üreticiler',
    'nav.our_story': 'Hikayemiz',
    'nav.login': 'Giriş Yap',
    'nav.profile': 'Profil ve Siparişler',
    'nav.admin': 'Yönetici Paneli',
    'nav.producer_panel': 'Üretici Paneli',
    'nav.logout': 'Çıkış Yap',
    'auth.title': 'Hoş Geldiniz',
    'auth.login': 'Giriş',
    'auth.register': 'Kayıt Ol',
    'auth.producer_register': 'Üretici Olarak Kayıt Ol',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.name': 'Ad Soyad',
    'auth.brand_name': 'Marka Adı',
    'auth.role': 'Hesap Tipi',
    'auth.role_user': 'Alıcı',
    'auth.role_producer': 'Üretici',
    'auth.login_success': 'Tekrar hoş geldiniz!',
    'auth.login_failed': 'Giriş başarısız',
    'auth.register_success': 'Hesabınız başarıyla oluşturuldu!',
    'auth.register_failed': 'Kayıt başarısız',
    'auth.login_subtitle': 'Hesabınıza erişmek için bilgilerinizi girin.',
    'auth.register_subtitle': 'Doğrudan üreticiden alışveriş yapmak için aramıza katılın.',
    'auth.no_account': 'Hesabınız yok mu? ',
    'auth.has_account': 'Zaten hesabınız var mı? ',
    'common.add_to_cart': 'Sepete Ekle',
    'common.stock': 'Stok',
    'common.price': 'Fiyat',
    'admin.dashboard': 'Panel',
    'admin.products': 'Ürünler',
    'admin.orders': 'Siparişler',
    'producer.my_products': 'Ürünlerim',
    'producer.add_product': 'Yeni Ürün Ekle',
    'hero.title': 'Özenle Üretildi.',
    'hero.subtitle': 'Bağımsız üreticilerden doğrudan ürünleri keşfedin. Aracı yok, sadece saf kalite ve dürüst tasarım.',
    'hero.cta': 'Koleksiyonu İncele',
    'home.latest_arrivals': 'Yeni Gelenler',
    'home.all': 'Hepsi',
    'home.no_products': 'Bu kategoride ürün bulunamadı.',
    'product.quantity': 'Adet',
    'product.warranty': '2 yıl üretici garantisi dahil',
    'product.shipping': '150 TL üzeri siparişlerde ücretsiz kargo',
    'product.back': 'Mağazaya Dön',
    'product.not_found': 'Ürün bulunamadı',
    'product.unavailable': 'Mevcut Değil',
    'product.out_of_stock': 'Stokta Yok',
  },
  en: {
    'nav.shop': 'Shop',
    'nav.producers': 'Producers',
    'nav.our_story': 'Our Story',
    'nav.login': 'Log in',
    'nav.profile': 'Profile & Orders',
    'nav.admin': 'Admin Dashboard',
    'nav.producer_panel': 'Producer Panel',
    'nav.logout': 'Log out',
    'auth.title': 'Welcome',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.producer_register': 'Register as Producer',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.brand_name': 'Brand Name',
    'auth.role': 'Account Type',
    'auth.role_user': 'Buyer',
    'auth.role_producer': 'Producer',
    'auth.login_success': 'Welcome back!',
    'auth.login_failed': 'Login failed',
    'auth.register_success': 'Account created successfully!',
    'auth.register_failed': 'Registration failed',
    'auth.login_subtitle': 'Enter your details to access your account.',
    'auth.register_subtitle': 'Join us to shop direct from producers.',
    'auth.no_account': "Don't have an account? ",
    'auth.has_account': 'Already have an account? ',
    'common.add_to_cart': 'Add to Cart',
    'common.stock': 'Stock',
    'common.price': 'Price',
    'admin.dashboard': 'Dashboard',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'producer.my_products': 'My Products',
    'producer.add_product': 'Add New Product',
    'hero.title': 'Crafted with intention.',
    'hero.subtitle': 'Discover goods directly from independent makers. No markups, just pure quality and honest design.',
    'hero.cta': 'Shop the Collection',
    'home.latest_arrivals': 'Latest Arrivals',
    'home.all': 'All',
    'home.no_products': 'No products found in this category.',
    'product.quantity': 'Quantity',
    'product.warranty': '2-year producer warranty included',
    'product.shipping': 'Free shipping on orders over $150',
    'product.back': 'Back to shop',
    'product.not_found': 'Product not found',
    'product.unavailable': 'Unavailable',
    'product.out_of_stock': 'Out of Stock',
  }
};

export const useLanguage = create<LanguageState>((set, get) => ({
  language: 'tr',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => translations[get().language][key] || key,
}));
